import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
  AiFillGithub,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/dev-ed-wave.png";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Kayanna Laster</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">Portfolio</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="/resume.pdf"
                  download="resume"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Kayanna Laster
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Full Stack Java Developer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Full Stack Java Developer with over half a decade's experience in
              Java and multiple years experiece with technologies such as
              MongoDB, MySQL, and React.
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <AiFillGithub />
              <AiFillLinkedin />
            </div>
            <div className="mx-auto  relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src="/ddd.png" layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h2 className="text-5xl py-1 dark:text-white ">My Experiences</h2>

            <p className="text-2xl py-2 leading-8 text-gray-800 dark:text-gray-200">
              I began my journey in software development at Drury University as
              a Computer Science Major with a mathematics and art minor.
            </p>

            <p className="text-2xl py-2 leading-8 text-gray-800 dark:text-gray-200">
              From my graduation, my journey as a Full Stack Java Developer
              began as an online computer science instructor at iDtech. Here I
              had the pleasure of teaching languages such as C++, Java, C#, and
              python.
            </p>

            <p className="text-2xl py-2 leading-8 text-gray-800 dark:text-gray-200">
              After my time at iD Tech, I began my life at Cognixia as a Full
              Stack Java Developer where I learned the skills and experience for
              Full Stack Java Development such as React, Spring, MySQL, and
              more.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={design} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Frontend Development
              </h3>
              <p className="py-2">
                Creating elegant, beautiful, and functional websites that will
                be sure to draw in a crowd.
              </p>
              <h4 className="py-4 text-teal-600">My Frontend Technologies</h4>
              <p className="text-gray-800 py-1">React</p>
              <p className="text-gray-800 py-1">Vue Js</p>
              <p className="text-gray-800 py-1">JS/HTML/CSS</p>
              <p className="text-gray-800 py-1">Angular</p>
              <p className="text-gray-800 py-1">BootStrap</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={code} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Backend Development
              </h3>
              <p className="py-2">
                Do you have an idea for your next great website but need help on
                the backend? I got you covered!
              </p>
              <h4 className="py-4 text-teal-600">My Backend Technologies</h4>
              <p className="text-gray-800 py-1">Spring</p>
              <p className="text-gray-800 py-1">MongoDB</p>
              <p className="text-gray-800 py-1">MySQL</p>
              <p className="text-gray-800 py-1">Hibernate</p>
              <p className="text-gray-800 py-1">Node.Js</p>
              <p className="text-gray-800 py-1">Express.JS</p>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h1 className="text-5xl py-1 dark:text-white ">Portofolio</h1>

            <p className="text-2xl py-2 leading-8 text-gray-800 dark:text-gray-200">
              Below are some of my favorite projects so far!
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <div>
                <h3 className="text-3xl py-1 dark:text-white ">
                  News Tracking Website!
                </h3>
              </div>
              <Image
                className="pic"
                width={"200px"}
                height={"100px"}
                layout="responsive"
                src="/p1.1.png"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <div>
                <h3 className="text-3xl py-1 dark:text-white ">
                  ChatGBT Clone!
                </h3>
              </div>
              <Image
                className="picture"
                width={"200px"}
                height={"100px"}
                layout="responsive"
                src="/p2.png"
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
